databases:
  - name: floneo-postgres
    databaseName: floneo
    user: floneo

services:
  # --- Backend API (server/) ---
  - name: floneo-backend
    type: web
    rootDir: server
    env: node
    plan: starter
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build || echo "build step skipped"
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: floneo-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      # Add your local dev origin and (later) the Render frontend URL
      - key: ALLOWED_ORIGINS
        value: https://example.com,http://localhost:3000
    disk:
      name: floneo-uploads
      mountPath: /server/uploads
      sizeGB: 1
    postDeployCommand: |
      npx prisma migrate deploy
      node -e "require('fs').mkdirSync('./uploads', { recursive: true }); console.log('uploads dir ready');"

  # --- Frontend (client/) ---
  - name: floneo-frontend
    type: web
    rootDir: client
    env: node
    plan: starter
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      # Will update to the backend's URL after first backend deploy
      - key: NEXT_PUBLIC_API_URL
        value: https://REPLACE_WITH_BACKEND_URL
      # For internal API routes
      - key: BACKEND_URL
        value: https://REPLACE_WITH_BACKEND_URL
