[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]
aptPkgs = ["curl"]

[phases.install]
cmds = ["npm ci --no-cache"]

[phases.build]
cmds = ["npm ci --no-cache", "npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && npm start"
