name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: fathima
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: lowcode_db
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0
      - name: Initialize and update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd server
          npm install
          cd ../client
          npm install
      - name: Run Prisma migrations
        run: |
          cd server
          npx prisma migrate dev --name ci-setup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Lint and Test
        run: |
          cd server
          npm run test || echo "No tests defined"
      - name: Start server (background)
        run: |
          cd server
          nohup npm start > server.log 2>&1 &
          sleep 15
          cat server.log
      - name: Check server is running
        run: |
          curl -I --retry 10 --retry-delay 2 http://localhost:5000 || exit 1