name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        cd server
        npm install
    - name: Lint and Test
      run: |
        cd server
        npm run test || echo "No tests defined"
    - name: Start server (background)
      run: |
        cd server
        nohup npm start &
        sleep 5
    - name: Check server is running
      run: |
        curl -I http://localhost:5000 || exit 1
